In [3]:
import pandas as pd 
import numpy as np

In [4]:
df = pd.read_csv('kidney_disease.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'kidney_disease.csv'

In [ ]:
df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [ ]:
df = df.drop(['id', 'age'], axis=1)

In [ ]:
df.head()

,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [ ]:
numerical = []
catgoals = []

for col in df.columns:
    if df[col].dtype == 'float64':
        numerical.append(col)
    else:
        catgoals.append(col)

for col in df.columns:
    if col in numerical:
        df.fillna({col: df[col].median()}, inplace=True)
    else:
        df.fillna({col: df[col].mode()[0]}, inplace=True)

In [ ]:
numerical

['bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo']

In [ ]:
catgoals

['rbc',
 'pc',
 'pcc',
 'ba',
 'pcv',
 'wc',
 'rc',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane',
 'classification']

In [ ]:
df.head()

,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,80.0,1.020,1.0,0.0,normal,normal,notpresent,notpresent,121.0,36.0,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,50.0,1.020,4.0,0.0,normal,normal,notpresent,notpresent,121.0,18.0,...,38,6000,5.2,no,no,no,good,no,no,ckd
2,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,...,31,7500,5.2,no,yes,no,poor,no,yes,ckd
3,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [ ]:
df['classification'].value_counts()

classification
ckd       248
notckd    150
ckd\t       2
Name: count, dtype: int64

In [ ]:
df['classification'] = df['classification'].replace(['ckd\t'], 'ckd')

In [ ]:
df['classification'].value_counts()

classification
ckd       250
notckd    150
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in catgoals:
    df[col] = le.fit_transform(df[col])

In [ ]:
ind_col = [col for col in df.columns if col != 'classification']
dep_col = 'classification'

In [ ]:
df['classification'] = le.fit_transform(df['classification'])

In [ ]:
df.head()

,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,80.0,1.020,1.0,0.0,1,1,0,0,121.0,36.0,...,32,72,34,1,4,1,0,0,0,0
1,50.0,1.020,4.0,0.0,1,1,0,0,121.0,18.0,...,26,56,34,0,3,1,0,0,0,0
2,80.0,1.010,2.0,3.0,1,1,0,0,423.0,53.0,...,19,70,34,0,4,1,1,0,1,0
3,70.0,1.005,4.0,0.0,1,0,1,0,117.0,56.0,...,20,62,19,1,3,1,1,1,1,0
4,80.0,1.010,2.0,0.0,1,1,0,0,106.0,26.0,...,23,68,27,0,3,1,0,0,0,0

In [ ]:
df.to_csv('kidney_index3.csv', index=False)